### ISSUE TITLE
Out of source builds fail

### ISSUE THREAD

**Issue by ideasman42** [chergert/gnome-builder#10]
Very straight forward out of source builds fail where in-source builds work fine.

Tested with ad2d32e8f349d82f1a2633c01a08f752e12bd6b4

With a fresh git checkout run:

  ../gnome-builder/autogen.sh --prefix=/opt/builder

... this works as expected.

then run `make`

    make[2]: Entering directory '/dsk/src/gnome-builder_build'
      CC       libide/libide_1_0_la-ide-source-view.lo
    ../gnome-builder/libide/ide-source-view.c:34:23: fatal error: ide-enums.h: No such file or directory
     #include "ide-enums.h"

**Comment by chergert** [comment]
Fixed in master.
