### ISSUE TITLE
core dump with anjuta generated project

### ISSUE THREAD

**Issue by bruci** [chergert/gnome-builder#12]
2015/04/17 20:57:24.2623  lapy:                 (null)[32732]:  WARNING: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2015/04/17 20:57:29.4870  lapy:         gb-application[32732]:  WARNING: "/home/bruno/devel/gtkbmi/configure.ac" is not a directory.
Segmentation fault (core dumped)

**Comment by chergert** [comment]
What version are you running? Also note that this is not the canonical repository (git://git.gnome.org/gnome-builder.git) and our bugtracker is at https://bugzilla.gnome.org/enter_bug.cgi?product=gnome-builder

**Comment by chergert** [comment]
This looks like a bug in our dummy VCS (version control system). If you run `git init` from the toplevel of your project, I think it will load.

**Comment by chergert** [comment]
Go ahead and try with the patch above, I've pushed that to master. I think it will fix your issue.

**Comment by bruci** [comment]
It was the issue with the VCS. I did a git init and it worked. Patch works also.
