### ISSUE TITLE
Files listed in .gitignore does not appears in side pane

### ISSUE THREAD

**Issue by gwinn** [chergert/gnome-builder#21]
Well. Even if file ignored it can be important and seems like it's bad idea to hide it from file list in side pane. I'm using gnome-builder shipped with Fedora 22.

**Comment by tobias47n9e** [comment]
I think that the default should be, that the ignored files are not shown. That would just clutter the overview 99 % of the time. Is there a use case where one frequently edits ignored files?

**Comment by TingPing** [comment]
> Is there a use case where one frequently edits ignored files?

One use-case that is *occasionally* useful personally is when I want to just inspect a generated file. I think overall 99% of whats in .gitignore is completely useless but once in a while its annoying.

**Comment by chergert** [comment]
We could probably add a toggle to the Display Options menu.

**Comment by gwinn** [comment]
> We could probably add a toggle to the Display Options menu.

it would be great

**Comment by chergert** [comment]
Fixed in 5052d4c48c381de3380ff5f830ca1fc67bece5bf.

**Comment by gwinn** [comment]
Awesome! Thanks!
