### ISSUE TITLE
Allow to "Rename to folder"

### ISSUE THREAD

**Issue by Salamandar** [chergert/gnome-builder#26]
In sublime text or github we can rename "auie.c" > "../auie.c" or "subfolder/auie.c".

That should be allowed in GnomeBuilder. :)

**Comment by chergert** [comment]
Fixed as of ead97ad98e45ca77c730bfced6436ab0e41892e3.

In the future, please report bugs to our bug tracker at https://bugzilla.gnome.org/enter_bug.cgi?product=gnome-builder
