### ISSUE TITLE
Clang dependency?

### ISSUE THREAD

**Issue by kozross** [chergert/gnome-builder#30]
I have just tried to install this (I'm on Parabola, which is a fully-free Arch), and I found that it depends on Clang. I'm curious whether this is an actual dependency of this project, or whether it's something that's been added by my distro for some reason.

**Comment by TingPing** [comment]
Yes it makes extensive use of clang. @chergert mentioned if gcc ever exposed the same functionality he would make use of it but atm clang is the only option.

**Comment by chergert** [comment]
Yes, we do need clang for all the IDE features for C/C++. Sadly, we don't have the APIs we need from GCC (yet). I've talked to a few GCC contributors who are hoping to use Builder as an example for why their employer should spend time working on these APIs.

So we will sit back and wait for that. In the mean time, I'm keeping track of all the APIs in clang that are absolutely horrible. It's actually a really annoying library to use.

**Comment by kozross** [comment]
Ah, I see. Well, I certainly look forward to news of your Clang-independence, if and when it happens. I'll close this for now, as my question has been answered.
