### ISSUE TITLE
Intentional non-support of menu support for XFCE?

### ISSUE THREAD

**Issue by kozross** [chergert/gnome-builder#31]
[Related Arch bug report][1]. Is there a reason for this, or is it just an omission?

[1]: https://bugs.archlinux.org/task/46047

**Comment by chergert** [comment]
We can certainly make it wider. It's just we tend to put that on GNOME applications since people might want to use something separate in their desktop of choice (Kdevelop in KDE for example).

**Comment by kozross** [comment]
I would certainly appreciate a widening of the net - it was surprising (and not in a good way, either) that when I tried to install this from my package manager, I got no menu entries!

**Comment by chergert** [comment]
Can you find me the necessary desktop name that needs to be there? I can add it today. (Probably just something like "XFCE" or "Xfce" or "xfce".

**Comment by TingPing** [comment]
I think an IDE has broad enough usage that it should not be limited to any DE. The use-cases for *OnlyShowIn* are only useful for things like `gnome-control-center` imo.

**Comment by chergert** [comment]
Good enough reason for me. Fixed in 1156a8f25036644e0210ca2ed3ebfda09cbb3f5c.
