### ISSUE TITLE
GbWorkbench won't tile left or right with GNOME's default keybindings

### ISSUE THREAD

**Issue by nikolowry** [chergert/gnome-builder#35]
GbGreeterWindow respects Super+Left, Super+Right and Super+Up - but GbWorkbench only respects Super+Up.

**Comment by chergert** [comment]
That means that the window's size request is too large to fit on half of your screen. On my screen here, it does fit on half, because it's a rather large screen. (We wont be optimizing for half width on small screens.)

**Comment by nikolowry** [comment]
What's the screen resolution minimum to have tiling enabled?  I'm on a 2880 * 1800 HiDPI and only use the treeview and bottom panel. 

It be nice to have it as an option/override - we all use software differently, strict UI rules like this makes it hard for people who don't use the software in the same manner as the creator/maintainer.

I want to make Builder my daily driver but my tiling motor reflexes are too much to shake (and not being able to find an up-to-date sass.lang file is another deal-breaker for me).

Great work nonetheless!

**Comment by chergert** [comment]
I just mean it would be disingenuous for me to go fix it this release only to be broken next release. We still have bunch of stuff that will likely land in the top bar as we add the planned features.

What we can probably do, is add some smarts to the size allocator of the search entry so that it can shrink. Right now, that size is dependent on GtkEntry:width-chars, which is not so forgiving.

**Comment by nikolowry** [comment]
All good - don't forget about us portable devs!

And I'd rather avoid going over to Bugzilla or combing through Mailing List archives of GtkSourceView - so if you know where I could grab an up to date sass/scss.lang file it wold be much appreciated! 

And thanks again

**Comment by chergert** [comment]
commit 774dc492373213d705c87997c1404140446f24cf should make it work on half width for now

**Comment by TingPing** [comment]
> Nevermind I found some up-to-date lang files. It's really strange to me they aren't included by default.

Well somebody has to go over to Bugzilla (and possibly poke somebody to get it through) :P

**Comment by nikolowry** [comment]
@chergert sorry to post on a closed issued, but wanted to say thanks again! Half the time I don't run a multi-monitor setup - so this was really helpful for me.
![screenshot from 2015-09-19 19-46-15](https://cloud.githubusercontent.com/assets/597310/9978601/610bb568-5f07-11e5-9b6f-908de0c7d6b6.png)

And @TingPing I grabbed them from gmate: https://github.com/gmate/gmate
