### ISSUE TITLE
Groovy Language

### ISSUE THREAD

**Issue by kana0011** [chergert/gnome-builder#42]
Are there plans to support groovy syntax highlighting in builder?

**Comment by TingPing** [comment]
Language files are a part of gtksourceview, it looks like there is an old issue over it there: https://bugzilla.gnome.org/show_bug.cgi?id=553894

**Comment by kana0011** [comment]
Wow, Thanks!

I created my own language file from the attached file from that thread, very useful.
https://gist.github.com/kana0011/f854cd0a59a8ccc90ad6

**Comment by TingPing** [comment]
Should post your improvements on that issue and maybe poke some people to get it merged.
