### ISSUE TITLE
homebrew: ec_glob.c: <pcre.h> not found

### ISSUE THREAD

**Issue by kirushyk** [chergert/gnome-builder#52]
Trying to build Builder against OS X using homebrew.

Looks like CFLAGS are not defined for pcre. Maybe pcre should be listed as dependency on OS X?

    ec_glob.c:31:10: fatal error: 'pcre.h' file not found
    #include <pcre.h>

**Comment by kirushyk** [comment]
As workaround, I temporary added `-I/usr/local/include` to it's `Makefile.am`.

**Comment by chergert** [comment]
I just added --enable-editorconfig=auto/yes/no. If auto/yes, pcre.h is checked. If yes, configure will fail if pcre.h is not found. Sadly we have no pkgconfig for pcre. Longer term, the libeditorconfig code is pretty horrible, I'd like to see it replaced writing something using GLib.
