### ISSUE TITLE
osx: Linux header <sys/prctl.h> is included unconditionally

### ISSUE THREAD

**Issue by kirushyk** [chergert/gnome-builder#57]
But there is no `<sys/prctl.h>` in Darwin:

    ide-application.c:31:10: fatal error: 'sys/prctl.h' file not found

**Comment by chergert** [comment]
Hrmm, are you on a branch or something?

```c
#ifdef __linux
# include <sys/prctl.h>
#endif
```

**Comment by kirushyk** [comment]
Hm, strange...

**Comment by kirushyk** [comment]
I see: https://github.com/chergert/gnome-builder/commit/dd067e9a1ff2d53d50d3cd56262a73195c36f18c
and https://bugzilla.gnome.org/show_bug.cgi?id=760174

**Comment by chergert** [comment]
I just pushed an updated tree to github, but generally `git://git.gnome.org/gnome-builder.git` is the tree of record.

**Comment by kirushyk** [comment]
Okay, pulled everything. This should be closed (:
