### ISSUE TITLE
 Issue with `make ` 

### ISSUE THREAD

**Issue by aissat** [chergert/gnome-builder#58]
Makefile:2513: recipe for target 'git/libide_1_0_la-ide-git-buffer-change-monitor.lo' failed
make[3]: *** [git/libide_1_0_la-ide-git-buffer-change-monitor.lo] Error 1
make[3]: Leaving directory '~/Downloads/gnome-builder-3.16.3/libide'
Makefile:1106: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '~/Downloads/gnome-builder-3.16.3/libide'
Makefile:602: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '~/Downloads/gnome-builder-3.16.3'
Makefile:513: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chergert** [comment]
Can you give me some details of the system this is being run on? Also, 3.16.3 is pretty old with how fast we have to move to get this thing generally usable in a short period of time.

**Comment by aissat** [comment]
yes thnx :) :+1:
