### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by aissat** [chergert/gnome-builder#59]
run autoconfig : +1: 
---

`gnome-builder - 3.19.0

 Options

  Prefix ............................... : /home/aye7/jhbuild/install
  Libdir ............................... : ${exec_prefix}/lib
  Optimized Build ...................... : no
  rdtscp ............................... : no

 Development Options

  Enable Debug ......................... : yes
  Enable Tracing ....................... : no
  Enable Profiling (-pg)................ : no
  Build Test Suite ..................... : no
  Build API reference .................. : no
  Use cross-referencing in API docs .... : yes

 Scripting

  Python ............................... : yes

 Plugins

  Autotools ............................ : yes
  Build Tools .......................... : yes
  C Language Pack ...................... : yes
  Clang ................................ : yes
  Command Bar .......................... : yes
  Contribute ........................... : yes
  Ctags ................................ : yes
  Devhelp .............................. : yes
  Editorconfig ......................... : yes
  Fpaste.org ........................... : yes
  GCC .................................. : yes
  Git Version Control .................. : yes
  Global File Search ................... : yes
  GNOME Code Assistance ................ : yes
  HTML Autocompletion .................. : yes
  HTML and Markdown Preview ............ : yes
  MinGW ................................ : yes
  Project Tree ......................... : yes
  Python GObject Introspection ......... : yes
  Python Jedi Autocompletion ........... : yes
  Python Language Pack ................. : yes
  Support .............................. : yes
  System Monitor ....................... : yes
  Symbol Tree .......................... : yes
  Todo ................................. : yes
  Terminal ............................. : yes
  Vala Language Pack ................... : yes
  XML Language Pack .................... : yes
`
run make  :-1:  
---
`error: Package 'libvala-0.32' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
Makefile:855: recipe for target 'libvala_pack_plugin_la_vala.stamp' failed
make[3]: *** [libvala_pack_plugin_la_vala.stamp] Error 1
make[3]: Leaving directory '/home/aye7/jhbuild/checkout/gnome-builder/plugins/vala-pack'
Makefile:549: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/aye7/jhbuild/checkout/gnome-builder/plugins'
Makefile:659: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/aye7/jhbuild/checkout/gnome-builder'
Makefile:570: recipe for target 'all' failed
make: *** [all] Error 2`

last bug when run gnome-builder :
---
`./gnome-builder: symbol lookup error: /home/aye7/jhbuild/install/lib/gnome-builder/libegg-private.so.0: undefined symbol: gtk_widget_queue_allocate`

**Comment by aissat** [comment]
for last bug i fixed 
just run 
jhbuild run gnome-builder

**Comment by aissat** [comment]
why this bug : 
`error: Package `libide-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories `

**Comment by chergert** [comment]
Please use bugzilla in the future. But this should have been fixed already.
