### ISSUE TITLE
Segmentation fault (core dumped) while editing html file

### ISSUE THREAD

**Issue by VigneshChennai** [chergert/gnome-builder#8]
Steps to reproduce.
1. $touch temp.html
2. $jhbuild run gnome-builder temp.html
3. Type '<!' without quotes in the editor.

OS: Archlinux
gnome-builder: latest code in git.

Support log file : https://gist.github.com/VigneshChennai/5c6ec6344fc28c68b9a9

**Comment by chergert** [comment]
Was on my list for today :) Fixed in master.

**Comment by VigneshChennai** [comment]
Just now rebuilt from git. Working now :+1: . Thanks :-)
