### ISSUE TITLE
Settings schema 'org.gnome.builder.editor.language' is not installed

### ISSUE THREAD

**Issue by zedtux** [chergert/gnome-builder#9]
The `jhbuild -m gnome-world build gnome-builder` command finished with success but when executing gnome-builder I got the following:

    ~/jhbuild • jhbuild run gnome-builder
    2015/02/12 08:47:27.7071  zedtux-iMac:              Builder[7479]:  MESSAGE: Initializing with Gtk+ version 3.15.6.
    2015/02/12 08:47:27.7342  zedtux-iMac:                  Gtk[7479]:  MESSAGE: Failed to load module "canberra-gtk-module"
    2015/02/12 08:47:27.7351  zedtux-iMac:                  Gtk[7479]:  MESSAGE: Failed to load module "canberra-gtk-module"
    2015/02/12 08:47:27.7351  zedtux-iMac:                  Gtk[7479]:    DEBUG: Connecting to session manager
    2015/02/12 08:47:27.7359  zedtux-iMac:             GLib-GIO[7479]:    ERROR: Settings schema 'org.gnome.builder.editor.language' is not installed
    
    [1]    7479 trace trap  jhbuild run gnome-builder

Did I missed something ? What can I do to solve this ?

**Comment by csoriano89** [comment]
glib-compile-schemas ~/jhbuild/install/share/glib-2.0/schemas/

I think nobody knows why its needed now. A bug in some part of the stack.

**Comment by chergert** [comment]
Yes, this is a bug in jhbuild and associated tooling. It should be fixed soon'ish.

Ryan also mentioned that `jhbuild postinst` would do the trick.

**Comment by zedtux** [comment]
> Ryan also mentioned that jhbuild postinst would do the trick.

Make it working !! Thank you ! :)

**Comment by matiasdelellis** [comment]
So, gnome-builder depend on gedit???

Please, there must be an alternative to this. :pensive:

**Comment by TingPing** [comment]
> So, gnome-builder depend on gedit???

No... nothing about this issue relates to gedit.

**Comment by chergert** [comment]
There was an issue with modelines relying on gedit preferences. That has been fixed in master.
